### ISSUE TITLE
Question about prediction

### ISSUE THREAD

**Issue by heitorsampaio** [Caff1982/football-predictions#1]
Hi Caff, 

Could you explain this output:

0 Prediction: 2 Odds diff: 0.11324374429110817
2 Prediction: 0 Odds diff: -0.24205590011481948
3 Prediction: 0 Odds diff: 0.07680052518844604
4 Prediction: 0 Odds diff: 0.1709744695757256
5 Prediction: 0 Odds diff: 0.21310876174406573
5 Prediction: 1 Odds diff: 0.12287358726773945
6 Prediction: 2 Odds diff: 0.13119223288127357
7 Prediction: 2 Odds diff: 0.4968955679248167
8 Prediction: 1 Odds diff: 0.2426253722773658
10 Prediction: 0 Odds diff: 0.36622321605682373

Is this the 10 games of the fixtures for the premier league, right?

but where in the prediction about Home winner, Draw, Away winner?

Cheers!

**Comment by heitorsampaio** [comment]
0 is home
1 is draw 
2 is away

is that right?

**Comment by Caff1982** [comment]
Hi,

Yeah that's right; 0 is home win, 1 is a draw and 2 is away win. 

Thanks for bring that to my attention, I'll make that clearer when I next update this repo.
